### ISSUE TITLE
Understading the Penalty Object

### ISSUE THREAD

**Issue by arose13** [scikit-learn-contrib/lightning#129]
I'm trying to implement a fairly complex custom penalty and I'm having a hard time understanding parts of the penalty object. From what I can understand it consists of 2 parts... 
1. A `regularization()` function. Which appears to compute the actual cost for given coefficients `coefs`
2. A `projection()` function. Which (might?) be the gradient?

Is this true and if so could I or someone else make a documentation contribution showing how to implement a custom Penalty() class.

**Comment by arose13** [comment]
To clarify, this is because I'm trying to implement the [Pliable Lasso](https://arxiv.org/pdf/1712.00484.pdf) in python and I'm trying to use your solvers. This model has 2 sets of coefficients that are being constrained, the coefs (beta (p)) and modifying coefs (theta (p x k)).

**Comment by vene** [comment]
Firstly, I should clarify that the the `Penalty` objects from `penalty.py` can only be used by the FISTA solvers. (In general it is quite difficult to have a generic mechanism for plug-and-play penalties, losses and solvers, because the solvers often need different APIs to interact with the problem.)

That said, the Penalty object might be a good way to implement Pliable Lasso with a FISTA solver for arbitrary losses. For a penalty function `Ω(w)`:

  - `regularization(w)` computes the value of the penalty term (i.e., the numerical value of `Ω(w)`).
  - `projection(w, alpha, L)` computes the approximation using the proximal operator of  function `alpha*Ω` (see section 2.3 of the [FISTA paper](https://people.rennes.inria.fr/Cedric.Herzet/Cedric.Herzet/Sparse_Seminar/Entrees/2012/11/12_A_Fast_Iterative_Shrinkage-Thresholding_Algorithmfor_Linear_Inverse_Problems_(A._Beck,_M._Teboulle)_files/Breck_2009.pdf), ie (i think) `argmin_x (alpha*Ω(x) + L/2) || x - (w - (1/L) ∇[alpha*Ω(w)]) ||^2)`

You can probably use the algo from the Pliable Lasso paper to compute the proximal operator. HTH
